# Generated by Django 4.1.4 on 2023-08-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reating',
            field=models.IntegerField(),
        ),
    ]
