# Generated by Django 4.1.4 on 2023-08-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_alter_book_reating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='reating',
            new_name='rating',
        ),
    ]
